DETECTOR_CONFIG:
  MODEL_TYPE: yolov6 # yolov5, yolov6, yolov7 or yolox
  MODEL_PATH: yolov6n.pt # yolov5s.pt, yolov6s.pt, yolov7s.pt, yolox_s.pth
  CONFIG_PATH: configs.yolox.yolox_s # yolox_s
  DEVICE: cuda:0
  CONFIDENCE_THRESHOLD: 0.25
  IOU_THRESHOLD: 0.45
  IMAGE_SIZE: 640
  SHOW: False
  SAVE: True

FILE_CONFIG:
  IMAGE_PATH: data/dog.jpg
  SAVE_PATH: data/dog_out.jpg
  OUTPUT_NAME: output
  COCO_YAML: torchyolo/configs/yolov6/coco.yaml # YOLOV6
  